### ISSUE TITLE
cidr type not mapped properly on a fold/4

### ISSUE THREAD

**Issue by rickpayne** [semiocast/pgsql#46]
Looks like some types are not being mapped before a fold:

```
1> pgsql_connection:simple_query("select prefix from prefixes_v6_unicast limit 1", C).
{{select,1},[{{cidr,<<"2403:c380::/32">>}}]}

2> pgsql_connection:fold(fun(A, Acc) -> io:format("A: ~p~n", [A]) end, null, "select prefix from prefixes_v6_unicast limit 1", C).
A: {{cidr,<<3,32,1,16,36,3,195,128,0,0,0,0,0,0,0,0,0,0,0,0>>}}
{ok,ok}
```

In the first case, for a cidr - you get a sane representation - but the second one is unusable in erlang (looks like the wire format?). Same for v4 cidr prefixes too.

**Comment by pguyot** [comment]
`fold/4` uses extended protocol where values can be returned in binary format, unlike `simple_query/2` which uses simple protocol where values are (more often) returned in text format. The issue is there is no parsing of CIDR in text or binary representations.  I am wondering how to render CIDR values if a parser is added. Like inet_cidr project? `{inet_address(), inet_address(), 1..128}`

**Comment by rickpayne** [comment]
Ah, ok. For now I'm pulling the bits I need out of the binary, but its a bit messy as I don't understand all the fields - can you point me at the decoder?
As for an erlang representation, I'd go with a tuple such as {ip_address(), int} where int is the mask length and ip_address() is as defined in inet (http://erlang.org/doc/man/inet.html#type-ip_address).

**Comment by pguyot** [comment]
The decoder is here:
https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/network.c#L229

**Comment by pguyot** [comment]
Eventually, I preferred to tag the results to prevent any ambiguity in the encoder.
CIDR values are encoded and decoded as `{cidr, inet_address(), 0..128}`
