### ISSUE TITLE
"invalid byte sequence for encoding" for bytea[] column

### ISSUE THREAD

**Issue by hengestone** [semiocast/pgsql#47]
I'm having trouble inserting data into a bytea[] column (ARRAY::bytea), e.g for a table defined as:
```
CREATE TABLE example (
   id                bytea,
   tpe               text,
   lst               bytea[]
);
```
The insert Query is
```
INSERT INTO example (id, tpe, lst) VALUES($1::bytea, $2, $3::bytea[]);
```
Using `pgsql_connection:extended_query(Query, Args, Conn)` with 
```
Args=[<<6,33,214,129,16,2,118,52,20,216,86,186,79,231,189,86>>,<<"b2b">>,[<<28,13,60,119,163,84,92,94,204,149,97,5,132,202,17,213>>]]
```
Gives the error
```
{error,{pgsql_error,[{severity,<<"ERROR">>},
                     {{unknown,86},<<"ERROR">>},
                     {code,<<"22021">>},
                     {message,<<"invalid byte sequence for encoding \"UTF8\": 0xa3">>},
                     {file,<<"wchar.c">>},
                     {line,<<"2017">>},
                     {routine,<<"report_invalid_encoding">>}]}}
```

Not sure if the query is not correct or this is a driver encoding issue. Any ideas?
Thanks!

**Comment by pguyot** [comment]
Sorry for the confusion with the API. You need to pass the array as:
`{array, Values}` with `Values :: [binary()]`

For example:
```
Args = [
  <<6,33,214,129,16,2,118,52,20,216,86,186,79,231,189,86>>,
  <<"b2b">>,
  {array, [<<28,13,60,119,163,84,92,94,204,149,97,5,132,202,17,213>>]}
],
{{insert, 0, 1}, []} = pgsql_connection:extended_query(
  "INSERT INTO example (id, tpe, lst) VALUES($1, $2, $3);", Args, Conn)).
```

Otherwise, the driver interprets your list as a string and passes it in text format to the network. PostgreSQL tries to decode it from the default encoding and then would try to cast it to an array.

Also, there normally is no need to cast the parameters in the SQL query.

**Comment by hengestone** [comment]
Thanks!
